### PR TITLE
add OrderedXmlObject whose constructor adds nodes in a specific order

### PR DESCRIPTION
**Pull request by dannyroberts**
This is very useful for having the mapper (your XmlObject subclass) control the order of its nodes, rather than push that out to the calling code. This comes up a lot in testing for example, where the XML-equal comparison enforces order, even if in your particular case the order isn't semantically meaningful.

(Reopened from https://github.com/emory-libraries/eulxml/pull/13)

### CODE REVIEW

**Comment by rlskoeser** [comment]
@dannyroberts I apologize for letting this sit for such a long time, I think your pull request came in when I was on leave and I forgot about it.

This looks useful, I know that order has sometimes been a problem with eulxml and some schemas are very specific about the required order of elements.

If you're still interested in getting this merged into eulxml, could you please provide some documentation with some examples of how to specify order and how it works, and also a unit test or two?

And I'll see if I can get the travis-ci tests fixed, they've been broken for a while unfortunately.

**Comment by dannyroberts** [comment]
@rlskoeser thanks for fixing those! Just (finally) made those updates. Let me know what you think!

**Comment by rlskoeser** [comment]
@dannyroberts thanks for making these updates.  Now that I see the tests I think I'm understanding better how it works.  I'd like to play with it some before I merge the pull request, but I think it looks reasonable, as long as we document the limitations clearly.  I hadn't quite registered that the specified order only affected content set at initialization time - although of course it is right there in your pull request title.

I've been thinking about the ordering and wondering if it wouldn't be useful to have some kind of ordering logic like this available in the XmlObject directly (optional, of course) and not just in a custom subclass.  However, in order to incorporate it there, we'd need to figure out a way to also allow constraining nodes that are added after the object has already been initialized, but I'm not sure yet how to make the ordering logic available in the field descriptors that actually create new xml elements.  It might also be nice to make the ordering logic more extensible, although I'm not sure yet what other scenarios we might see.

If you have any additional thoughts on this please let me know.

**Comment by dannyroberts** [comment]
I haven't looked too deep, but my understanding is that enforcing order like you're saying (rather than just specifying a default order for the constructor) is a fair bit more involved. Currently the field's manager is responsible for taking a node and appending its xml to it (or inserting in the right place), and so it would also have to know about field order.

Up to you whether you want this in now or want to wait until you've thought about how to more fully integrate the feature.

**Comment by rlskoeser** [comment]
Sorry I never dealt with this (you've probably forgotten all about it by now).  It seems weird to me to support order in the constructor and not elsewhere, but I do think it's valuable.  I've created a new issue and referenced your pull request, so hopefully we can add proper order control at some point.

**Pull request closed without merging**
